aproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('search/', views.post_search, name='post_search'),
    path('create/', views.post_create, name='post_create'),
    path('<int:id>/', views.post_detail, name='post_detail'),
]

blog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post


class SearchForm(forms.Form):
    keyword = forms.CharField()


class PostForm(forms.ModelForm): # take fields from already created models in models.py
    class Meta:
        model = Post
        fields = ['title', 'content', 'category', 'image']

blog/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Post
from django.db.models import Q

from .forms import SearchForm, PostForm

# Create your views here.

# def post_list(request):
#     posts = Post.objects.all().order_by('-created_at')
#     # link = reverse('post_detail', args=[id])
#     return render(request, 'blog/post_list.html', {'posts': posts})

def post_list(request):
    posts = Post.objects.all().order_by('-created_at')
    form = SearchForm()
    key = request.GET.get('keyword')

    if key:
        posts = posts.filter(Q(content__icontains = key) | Q(title__icontains = key)) 

    return render(request, 'blog/post_list.html', {'posts': posts, 'form': form})


def post_detail(request, id):
    post = Post.objects.get(id=id)
    return render(request, 'blog/post_detail.html', {'post': post})


# def post_search(request):

#     content_q = request.GET.get('content_q')
#     # title_q = request.GET.get('title_q')

#     posts = Post.objects.all()

#     if content_q:
#         posts = posts.filter(Q(content__icontains = content_q) | Q(title__icontains = content_q)) 

#     # if title_q:
#     #     posts = posts.filter(title__icontains = title_q)

#     return render(request, 'blog/post_search.html', {'posts': posts})


def post_search(request):

    content_q = request.GET.get('content_q')
    title_q = request.GET.get('title_q')

    posts = Post.objects.all()

    if content_q:
        posts = posts.filter(Q(content__icontains = content_q) | Q(title__icontains = content_q)) 

    if title_q:
        posts = posts.filter(title__icontains = title_q)

    return render(request, 'blog/post_search.html', {'posts': posts})

# def post_search(request):

#     content_q = request.GET.get('content_q')
#     title_q = request.GET.get('title_q')

#     posts = Post.objects.all()

#     if content_q:
#         posts = posts.filter(Q(content__icontains = content_q) | Q(title__icontains = content_q))

#     if title_q:
#         posts = posts.filter(title__icontains = title_q)

#     return render(request, 'blog/post_search.html', {'posts': posts})


def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('blog:post_list')  # Redirect to post list page after successful form submission
    else:
        form = PostForm()
    return render(request, 'blog/create_post.html', {'form': form})

templates/blog/create_post.html
<!-- templates/blog/create_post.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Post</title>
</head>
<body>
    <h1>Create Post</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

templates/blog/post_detail.html
<!-- blog/templates/blog/post_list.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Post List</title>
</head>
<body>

    <h2>{{ post.title }}</h2>
    <img src="{{post.image.url }}" alt="post_image">
    <p>{{ post.content }}</p>
    <p>Category: {{ post.category }}</p>
    <p>Published on: {{ post.created_at }}</p>

    <a href="{% url 'blog:post_list' %}">Back to Post List</a>

</body>
</html>

templates/blog/post_list.html
<!-- blog/templates/blog/post_list.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Post List</title>
</head>
<body>

    <form method="get" action="{% url 'blog:post_list' %}">
        <!-- {% csrf_token %} -->
        {{ form.as_p }}

        <button type="submit">Search</button>
    </form>

    <br>
    <a href="{% url 'blog:post_create' %}">Create a post</a>

    <h1>Blog Posts</h1>
    <ul>
        {% for post in posts %}
            <li>
                <a href="{% url 'blog:post_detail' post.id %}"><h2>{{ post.title }}</h2></a> 
                <!-- href="/blog/{{post.id}}" alternatively-->
                <img src="{{post.image.url }}" alt="post_image">
                <p>{{ post.content }}</p>
                <p>Category: {{ post.category }}</p>
                <p>Published on: {{ post.created_at }}</p>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

templates/blog/post_search.html
<form method="get" action="">

    {% csrf_token %}
    <label for="content_q">Search in content: </label>
    <input type="text" name="content_q">
    <br>

    <!-- <label for="title_q">Search in title: </label>
    <input type="text" name="title_q">
    <br> -->
    
    <label for="title_q">Select a title</label>
    <select name="title_q" id="title_q">
        <option value="">--Any--</option>
        {% for post in posts %}
        <option value="{{ post.title }}">{{ post.title }}</option>
        {% endfor %}
    </select>
    <br>

    <button type="submit">Search</button>

</form>

<a href="{% url 'blog:post_list' %}">Post Lists</a>

<h1>Blog Posts</h1>
    <ul>
        {% for post in posts %}
            <li>
                <a href="{% url 'blog:post_detail' post.id %}"><h2>{{ post.title }}</h2></a> 
                <!-- href="/blog/{{post.id}}" alternatively-->
                <img src="{{post.image.url }}" alt="post_image">
                <p>{{ post.content }}</p>
                <p>Category: {{ post.category }}</p>
                <p>Published on: {{ post.created_at }}</p>
            </li>
        {% endfor %}
    </ul>